export interface TimelineEntry {
    id: string;
    date: string;
    vibe_score: number;
    appetite: 'good' | 'picky' | 'none';
    litter: 'normal' | 'off';
    note?: string;
    photoUrl?: string;
}

const VIBE_LABELS: Record<number, string> = {
    1: '😊 Happy',
    2: '😌 Quiet',
    3: '😟 Anxious',
    4: '🫣 Hide-y',
    5: '⚡ Energetic'
};

const APPETITE_LABELS: Record<string, string> = {
    good: '🍲 Good',
    picky: '🥗 Picky',
    none: '🚫 None'
};

const LITTER_LABELS: Record<string, string> = {
    normal: '✅ Normal',
    off: '⚠️ Concerning'
};

/**
 * Generate a Vet Export PDF from timeline entries
 * @param entries - Timeline entries to include in export
 * @param catName - Name of the cat
 * @param days - Number of days included in export
 */
export async function generateVetExport(entries: TimelineEntry[], catName: string, days: number): Promise<void> {
    // Dynamic import to keep main bundle small (Nova's request)
    const { default: jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(241, 90, 34); // Meowmo orange
    doc.text(`${catName}'s Health Timeline`, pageWidth / 2, 20, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(93, 109, 126); // Neutral gray
    doc.text(`Export: Last ${days} Days | Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });

    // Summary Stats
    const avgVibe = entries.reduce((sum, e) => sum + e.vibe_score, 0) / entries.length;
    const concerningDays = entries.filter(e => e.litter === 'off' || e.appetite === 'none').length;

    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text(`Total Logs: ${entries.length} | Avg Vibe: ${avgVibe.toFixed(1)} | Concerning Days: ${concerningDays}`, 14, 38);

    // Clinical Insights Section (Brain 2.0)
    const { analyzeHealthPatterns } = await import('./health_analysis_service');
    const insights = analyzeHealthPatterns(entries, catName);

    if (insights.length > 0) {
        doc.setFillColor(245, 245, 245);
        doc.roundedRect(14, 42, pageWidth - 28, 12 + (insights.length * 6), 3, 3, 'F');

        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(241, 90, 34);
        doc.text('Clinical Observations & Trends', 18, 48);

        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(50, 50, 50);

        insights.forEach((insight, index) => {
            doc.text(`• [${insight.severity.toUpperCase()}] ${insight.title}: ${insight.description.substring(0, 80)}...`, 18, 54 + (index * 6));
        });
    }

    const tableStartY = insights.length > 0 ? 60 + (insights.length * 6) : 45;

    // Timeline Table
    const tableData = entries.map(entry => [
        new Date(entry.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
        VIBE_LABELS[entry.vibe_score] || `Vibe ${entry.vibe_score}`,
        APPETITE_LABELS[entry.appetite] || entry.appetite,
        LITTER_LABELS[entry.litter] || entry.litter,
        entry.note || '-'
    ]);

    autoTable(doc, {
        startY: tableStartY,
        head: [['Date', 'Mood', 'Appetite', 'Litter', 'Notes']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [241, 90, 34], // Meowmo orange
            textColor: 255,
            fontStyle: 'bold',
            fontSize: 9
        },
        bodyStyles: {
            fontSize: 8,
            textColor: [93, 109, 126]
        },
        alternateRowStyles: {
            fillColor: [254, 243, 199] // Light orange
        },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 30 },
            2: { cellWidth: 25 },
            3: { cellWidth: 30 },
            4: { cellWidth: 'auto' }
        }
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY || tableStartY;
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Meowmo - Your Cat\'s Health Companion', pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save
    const filename = `${catName.replace(/\s+/g, '-')}-health-export-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);

    console.log(`[VET_EXPORT] Generated PDF: ${filename}`);
}

/**
 * Check if user has access to export based on premium status
 * @param isPremium - Whether user has premium subscription
 * @param requestedDays - Number of days user wants to export
 * @returns True if user can export, false if paywall should trigger
 */
export function canExport(isPremium: boolean, requestedDays: number): boolean {
    const FREE_TIER_LIMIT = 7;

    if (isPremium) return true;
    return requestedDays <= FREE_TIER_LIMIT;
}

/**
 * Get export options available to user
 * @param isPremium - Whether user has premium subscription
 * @returns Array of day options user can export
 */
export function getExportOptions(isPremium: boolean): number[] {
    if (isPremium) {
        return [7, 14, 30, 90];
    }
    return [7]; // Free tier only
}
